name: rediones
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  dio:
  file_picker:
  badges:
  intl:
  clipboard:
  camera:
  path_provider:
  equatable:
  flutter_boxicons:
  flutter_screenutil:
  flutter_spinkit:
  connectivity_plus:
  cached_network_image:
  flutter_launcher_icons:
  flutter_native_splash:
  photo_view:
  flutter_reaction_button:
  video_editor:
  photofilters:
  chatview:
  timeago:
  shared_preferences:
  flutter_svg:
  photo_gallery:
  transparent_image:
  flutter_rating_stars:
  helpers:
  glassmorphism:
  story_view:
  socket_io_client:
  chat_bubbles:
  flutter_video_info:
  permission_handler:
  go_router:
  flutter_riverpod:
  animated_switcher_plus:
  flutter_image_compress:
  progressive_image:
  flutter_staggered_animations:
  crop_image:
  skeletonizer:
  path:
  get_it:
  flex_color_scheme:
  video_player:
  fijkplayer: ^0.11.0
  dropdown_button2:
  animated_snack_bar:
  awesome_notifications_core: ^0.9.0
  awesome_notifications:
  uuid:
  camera_camera:
  image:
  flutter_quick_video_encoder:
  flutter_keyboard_visibility:
  zero_story_editor:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  mime:
  app_links:
  video_thumbnail:

dev_dependencies:
  flutter_test:
    sdk: flutter

  isar_generator: ^3.1.0+1
  build_runner:
  flutter_lints: ^4.0.0


flutter_icons:
  image_path_android: "assets/Icon.png"
  image_path_ios: "assets/Icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/Icon.png"
  min_sdk_android: 29
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#101010"
  android: true
  ios: true
  image: "assets/Icon.png"

  android_12:
    color: "#FFFFFF"
    color_dark: "#101010"
    image: "assets/Icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito-Italic.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-Medium.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf